apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: notify-alert
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Sends a security alert"
  runtime: nodejs
  image: "nuclio/processor-amqpconsume:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  build:
    functionSourceCode: dmFyIGFtcXAgPSByZXF1aXJlKCdhbXFwbGliJyk7Cgpjb25zdCB1cmwgPSAiYW1xcDovL2d1ZXN0Omd1ZXN0QDE5Mi4xNjguMS4xNjQ6NTY3MiI7CmNvbnN0IHVzZXJRdWV1ZSA9ICJub3RpZnkvdXNlciI7CmNvbnN0IGtleSA9ICJzZWN1cml0eSIKCmZ1bmN0aW9uIGJpbjJzdHJpbmcoYXJyYXkpIHsKICAgIHZhciByZXN1bHQgPSAiIjsKICAgIGZvcih2YXIgaSA9IDA7IGkgPCBhcnJheS5sZW5ndGg7ICsraSkgewogICAgICAgIHJlc3VsdCArPSAoU3RyaW5nLmZyb21DaGFyQ29kZShhcnJheVtpXSkpOwogICAgfQogICAgcmV0dXJuIHJlc3VsdDsKfQoKZXhwb3J0cy5oYW5kbGVyID0gZnVuY3Rpb24oY29udGV4dCwgZXZlbnQpIHsKICAgIHZhciBwYXJzZWRFdmVudCA9IEpTT04ucGFyc2UoSlNPTi5zdHJpbmdpZnkoZXZlbnQpKTsKICAgIHZhciBhbGVydCA9IGJpbjJzdHJpbmcocGFyc2VkRXZlbnQuYm9keS5kYXRhKTsKCiAgICBhbXFwLmNvbm5lY3QodXJsKS50aGVuKGZ1bmN0aW9uKGNvbm4pIHsKICAgICAgICByZXR1cm4gY29ubi5jcmVhdGVDaGFubmVsKCkudGhlbihmdW5jdGlvbihjaCkgewogICAgICAgICAgICB2YXIgb2sgPSBjaC5hc3NlcnRFeGNoYW5nZSh1c2VyUXVldWUsICd0b3BpYycsIHtkdXJhYmxlOiBmYWxzZX0pOwogICAgICAgICAgICByZXR1cm4gb2sudGhlbihmdW5jdGlvbigpIHsKICAgICAgICAgICAgICAgIGNoLnB1Ymxpc2godXNlclF1ZXVlLCBrZXksIEJ1ZmZlci5mcm9tKGFsZXJ0KSk7CiAgICAgICAgICAgICAgICBjb25zb2xlLmxvZyhgU2VudCAke2FsZXJ0fSBvbiAke3VzZXJRdWV1ZX0vJHtrZXl9YCk7CiAgICAgICAgICAgICAgICByZXR1cm4gY2guY2xvc2UoKTsKICAgICAgICAgICAgfSk7CiAgICAgICAgfSkuZmluYWxseShmdW5jdGlvbigpIHsgY29ubi5jbG9zZSgpOyAgfSkKICAgIH0pLmNhdGNoKGNvbnNvbGUubG9nKTsKCiAgICBjb250ZXh0LmNhbGxiYWNrKGFsZXJ0KTsKfTs=
    commands:
      - "npm install amqplib"
    codeEntryType: sourceCode
  platform: {}