apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: notify-alert
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Sends a security alert"
  runtime: nodejs
  image: "nuclio/processor-amqpconsume:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  build:
    functionSourceCode: Y29uc3QgYW1xcCA9IHJlcXVpcmUoImFtcXBsaWIvY2FsbGJhY2tfYXBpIik7Cgpjb25zdCB1cmwgPSAiYW1xcDovL2d1ZXN0Omd1ZXN0QDE5Mi4xNjguMS4xNjQ6NTY3MiI7Cgpjb25zdCB1c2VyUXVldWUgPSAibm90aWZ5L3VzZXIiOwpjb25zdCBrZXkgPSAic2VjdXJpdHkiCgpjb25zdCBub3RpZnlBbGVydCA9IChhbGVydCkgPT4gewogICAgYW1xcC5jb25uZWN0KHVybCwgKGNvbm5lY3Rpb25FcnJvciwgY29ubmVjdGlvbikgPT4gewogICAgICAgIGlmIChjb25uZWN0aW9uRXJyb3IpCiAgICAgICAgICAgIHRocm93IGNvbm5lY3Rpb25FcnJvcjsKCiAgICAgICAgY29ubmVjdGlvbi5jcmVhdGVDaGFubmVsKChjaGFubmVsRXJyb3IsIGNoYW5uZWwpID0+IHsKICAgICAgICAgICAgaWYgKGNoYW5uZWxFcnJvcikKICAgICAgICAgICAgICAgIHRocm93IGNoYW5uZWxFcnJvcjsKCiAgICAgICAgICAgIGNoYW5uZWwuYXNzZXJ0RXhjaGFuZ2UodXNlclF1ZXVlLCAidG9waWMiLCB7ZHVyYWJsZTogZmFsc2V9KTsKCiAgICAgICAgICAgIGNoYW5uZWwucHVibGlzaCh1c2VyUXVldWUsIGtleSwgQnVmZmVyLmZyb20oYWxlcnQpKTsKCiAgICAgICAgICAgIGNvbnNvbGUubG9nKGBTZW50ICR7YWxlcnR9IG9uICR7dXNlclF1ZXVlfS8ke2tleX1gKTsKCiAgICAgICAgICAgIGNoYW5uZWwuY2xvc2UoKTsKICAgICAgICB9KTsKICAgIH0pOwp9Cgpjb25zdCBiaW5hcnlUb1N0cmluZyA9IChhcnJheSkgPT4gewogICAgbGV0IHJlc3VsdCA9ICIiOwogICAgZm9yIChsZXQgaSA9IDA7IGkgPCBhcnJheS5sZW5ndGg7ICsraSkKICAgICAgICByZXN1bHQgKz0gKFN0cmluZy5mcm9tQ2hhckNvZGUoYXJyYXlbaV0pKTsKCiAgICByZXR1cm4gcmVzdWx0Owp9CgpleHBvcnRzLmhhbmRsZXIgPSAoY29udGV4dCwgZXZlbnQpID0+IHsKICAgIGNvbnN0IHBhcnNlZEV2ZW50ID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeShldmVudCkpOwogICAgY29uc3QgYWxlcnQgPSBiaW5hcnlUb1N0cmluZyhwYXJzZWRFdmVudC5ib2R5LmRhdGEpOwoKICAgIG5vdGlmeUFsZXJ0KGFsZXJ0KTsKCiAgICBjb250ZXh0LmNhbGxiYWNrKGFsZXJ0KTsKfQ==
    commands:
      - "npm install amqplib"
    codeEntryType: sourceCode
  platform: {}