apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: notify-police
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Sends a security alert to the police"
  runtime: nodejs
  image: "nuclio/processor-amqpconsume:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    amqp-police-trigger:
      class: ""
      kind: rabbit-mq
      url: "amqp://guest:guest@192.168.1.164:5672"
      attributes:
        exchangeName: notify/police
        queueName: notify/police
        topics:
          - security
  build:
    functionSourceCode: Y29uc3QgYW1xcCA9IHJlcXVpcmUoImFtcXBsaWIvY2FsbGJhY2tfYXBpIik7Cgpjb25zdCB1cmwgPSAiYW1xcDovL2d1ZXN0Omd1ZXN0QDE5Mi4xNjguMS4xNjQ6NTY3MiI7Cgpjb25zdCBwb2xpY2VRdWV1ZSA9ICJub3RpZnkvcG9saWNlL3Rlcm1pbmFsIjsKCmNvbnN0IG5vdGlmeVBvbGljZSA9IChhbGVydCkgPT4gewogICAgYW1xcC5jb25uZWN0KHVybCwgKGNvbm5lY3Rpb25FcnJvciwgY29ubmVjdGlvbikgPT4gewogICAgICAgIGlmIChjb25uZWN0aW9uRXJyb3IpCiAgICAgICAgICAgIHRocm93IGNvbm5lY3Rpb25FcnJvcjsKCiAgICAgICAgY29ubmVjdGlvbi5jcmVhdGVDaGFubmVsKChjaGFubmVsRXJyb3IsIGNoYW5uZWwpID0+IHsKICAgICAgICAgICAgaWYgKGNoYW5uZWxFcnJvcikKICAgICAgICAgICAgICAgIHRocm93IGNoYW5uZWxFcnJvcjsKCiAgICAgICAgICAgIGNoYW5uZWwuYXNzZXJ0UXVldWUocG9saWNlUXVldWUsIHtkdXJhYmxlOiBmYWxzZX0pOwoKICAgICAgICAgICAgY2hhbm5lbC5zZW5kVG9RdWV1ZShwb2xpY2VRdWV1ZSwgQnVmZmVyLmZyb20oYWxlcnQpKTsKCiAgICAgICAgICAgIGNvbnNvbGUubG9nKGBTZW50ICR7YWxlcnR9IG9uICR7cG9saWNlUXVldWV9YCk7CgogICAgICAgICAgICBjaGFubmVsLmNsb3NlKCk7CiAgICAgICAgfSk7CiAgICB9KTsKfQoKY29uc3QgYmluYXJ5VG9TdHJpbmcgPSAoYXJyYXkpID0+IHsKICAgIGxldCByZXN1bHQgPSAiIjsKICAgIGZvciAobGV0IGkgPSAwOyBpIDwgYXJyYXkubGVuZ3RoOyArK2kpCiAgICAgICAgcmVzdWx0ICs9IChTdHJpbmcuZnJvbUNoYXJDb2RlKGFycmF5W2ldKSk7CgogICAgcmV0dXJuIHJlc3VsdDsKfQoKZXhwb3J0cy5oYW5kbGVyID0gKGNvbnRleHQsIGV2ZW50KSA9PiB7CiAgICBjb25zdCBwYXJzZWRFdmVudCA9IEpTT04ucGFyc2UoSlNPTi5zdHJpbmdpZnkoZXZlbnQpKTsKICAgIGNvbnN0IGFsZXJ0ID0gYmluYXJ5VG9TdHJpbmcocGFyc2VkRXZlbnQuYm9keS5kYXRhKTsKCiAgICBub3RpZnlQb2xpY2UoYWxlcnQpOwp9
    commands:
      - "npm install amqplib"
    codeEntryType: sourceCode
  platform: {}