apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: notify-user
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Sends a security alert to the user"
  runtime: nodejs
  image: "nuclio/processor-amqpconsume:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    amqp-user-trigger:
      class: ""
      kind: rabbit-mq
      url: "amqp://guest:guest@192.168.1.164:5672"
      attributes:
        exchangeName: notify/user
        queueName: notify/user
        topics:
          - security
  build:
    functionSourceCode: Y29uc3QgYW1xcCA9IHJlcXVpcmUoJ2FtcXBsaWInKTsKCmNvbnN0IHVybCA9ICJhbXFwOi8vZ3Vlc3Q6Z3Vlc3RAMTkyLjE2OC4xLjE2NDo1NjcyIjsKY29uc3QgdXNlclRlcm1pbmFsUXVldWUgPSAibm90aWZ5L3VzZXIvdGVybWluYWwiOwoKZnVuY3Rpb24gYmluMnN0cmluZyhhcnJheSkgewogICAgbGV0IHJlc3VsdCA9ICIiOwogICAgZm9yIChsZXQgaSA9IDA7IGkgPCBhcnJheS5sZW5ndGg7ICsraSkgewogICAgICAgIHJlc3VsdCArPSAoU3RyaW5nLmZyb21DaGFyQ29kZShhcnJheVtpXSkpOwogICAgfQogICAgcmV0dXJuIHJlc3VsdDsKfQoKZnVuY3Rpb24gbm90aWZ5VXNlcihhbGVydCkgewogICAgYW1xcC5jb25uZWN0KHVybCkudGhlbihmdW5jdGlvbihjb25uZWN0aW9uKSB7CiAgICAgICAgcmV0dXJuIGNvbm5lY3Rpb24uY3JlYXRlQ2hhbm5lbCgpLnRoZW4oZnVuY3Rpb24oY2hhbm5lbCkgewogICAgICAgICAgICBjb25zdCBvayA9IGNoYW5uZWwuYXNzZXJ0UXVldWUodXNlclRlcm1pbmFsUXVldWUsIHtkdXJhYmxlOiBmYWxzZX0pOwogICAgICAgICAgICByZXR1cm4gb2sudGhlbihmdW5jdGlvbihfcW9rKSB7CiAgICAgICAgICAgICAgICBjaGFubmVsLnNlbmRUb1F1ZXVlKHVzZXJUZXJtaW5hbFF1ZXVlLCBCdWZmZXIuZnJvbShhbGVydCkpOwogICAgICAgICAgICAgICAgY29uc29sZS5sb2coYFNlbnQgJHthbGVydH0gb24gJHt1c2VyVGVybWluYWxRdWV1ZX1gKTsKICAgICAgICAgICAgICAgIHJldHVybiBjaGFubmVsLmNsb3NlKCk7CiAgICAgICAgICAgIH0pOwogICAgICAgIH0pLmZpbmFsbHkoZnVuY3Rpb24oKSB7CiAgICAgICAgICAgIGNvbm5lY3Rpb24uY2xvc2UoKTsKICAgICAgICB9KTsKICAgIH0pLmNhdGNoKGNvbnNvbGUud2Fybik7Cn0KCmV4cG9ydHMuaGFuZGxlciA9IGZ1bmN0aW9uKGNvbnRleHQsIGV2ZW50KSB7CiAgICBjb25zdCBwYXJzZWRFdmVudCA9IEpTT04ucGFyc2UoSlNPTi5zdHJpbmdpZnkoZXZlbnQpKTsKICAgIGNvbnN0IGFsZXJ0ID0gYmluMnN0cmluZyhwYXJzZWRFdmVudC5ib2R5LmRhdGEpOwoKICAgIGNvbnRleHQuY2FsbGJhY2soYWxlcnQpOwoKICAgIG5vdGlmeVVzZXIoYWxlcnQpOwp9Ow==
    commands:
      - "npm install amqplib"
    codeEntryType: sourceCode
  platform: {}