apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: notify-alert
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Sends a security alert"
  runtime: nodejs
  image: "nuclio/processor-amqpconsume:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  build:
    functionSourceCode: Y29uc3QgYW1xcCA9IHJlcXVpcmUoJ2FtcXBsaWInKTsKCmNvbnN0IHVybCA9ICJhbXFwOi8vZ3Vlc3Q6Z3Vlc3RAMTkyLjE2OC4xLjE2NDo1NjcyIjsKY29uc3QgdXNlclF1ZXVlID0gIm5vdGlmeS91c2VyIjsKY29uc3Qga2V5ID0gInNlY3VyaXR5IgoKZnVuY3Rpb24gYmluMnN0cmluZyhhcnJheSkgewogICAgbGV0IHJlc3VsdCA9ICIiOwogICAgZm9yIChsZXQgaSA9IDA7IGkgPCBhcnJheS5sZW5ndGg7ICsraSkgewogICAgICAgIHJlc3VsdCArPSAoU3RyaW5nLmZyb21DaGFyQ29kZShhcnJheVtpXSkpOwogICAgfQogICAgcmV0dXJuIHJlc3VsdDsKfQoKZnVuY3Rpb24gbm90aWZ5QWxlcnQoYWxlcnQpIHsKICAgIGFtcXAuY29ubmVjdCh1cmwpLnRoZW4oZnVuY3Rpb24gKGNvbm5lY3Rpb24pIHsKICAgICAgICByZXR1cm4gY29ubmVjdGlvbi5jcmVhdGVDaGFubmVsKCkudGhlbihmdW5jdGlvbiAoY2hhbm5lbCkgewogICAgICAgICAgICBjb25zdCBvayA9IGNoYW5uZWwuYXNzZXJ0RXhjaGFuZ2UodXNlclF1ZXVlLCAndG9waWMnLCB7ZHVyYWJsZTogZmFsc2V9KTsKICAgICAgICAgICAgcmV0dXJuIG9rLnRoZW4oZnVuY3Rpb24gKCkgewogICAgICAgICAgICAgICAgY2hhbm5lbC5wdWJsaXNoKHVzZXJRdWV1ZSwga2V5LCBCdWZmZXIuZnJvbShhbGVydCkpOwogICAgICAgICAgICAgICAgY29uc29sZS5sb2coYFNlbnQgJHthbGVydH0gb24gJHt1c2VyUXVldWV9LyR7a2V5fWApOwogICAgICAgICAgICAgICAgcmV0dXJuIGNoYW5uZWwuY2xvc2UoKTsKICAgICAgICAgICAgfSk7CiAgICAgICAgfSkuZmluYWxseShmdW5jdGlvbiAoKSB7CiAgICAgICAgICAgIGNvbm5lY3Rpb24uY2xvc2UoKTsKICAgICAgICB9KQogICAgfSkuY2F0Y2goY29uc29sZS5sb2cpOwp9CgpleHBvcnRzLmhhbmRsZXIgPSBmdW5jdGlvbihjb250ZXh0LCBldmVudCkgewogICAgY29uc3QgcGFyc2VkRXZlbnQgPSBKU09OLnBhcnNlKEpTT04uc3RyaW5naWZ5KGV2ZW50KSk7CiAgICBjb25zdCBhbGVydCA9IGJpbjJzdHJpbmcocGFyc2VkRXZlbnQuYm9keS5kYXRhKTsKCiAgICBub3RpZnlBbGVydChhbGVydCk7CgogICAgY29udGV4dC5jYWxsYmFjayhhbGVydCk7Cn07
    commands:
      - "npm install amqplib"
    codeEntryType: sourceCode
  platform: {}