apiVersion: "nuclio.io/v1"
kind: Function
metadata:
  name: notify-police
  namespace: nuclio
spec:
  handler: "main:handler"
  description: "Sends a security alert to the police"
  runtime: nodejs
  image: "nuclio/processor-amqpconsume:latest"
  minReplicas: 1
  maxReplicas: 1
  targetCPU: 75
  triggers:
    amqp-police-trigger:
      class: ""
      kind: rabbit-mq
      url: "amqp://guest:guest@192.168.1.164:5672"
      attributes:
        exchangeName: notify/police
        queueName: notify/police
        topics:
          - security
  build:
    functionSourceCode: dmFyIGFtcXAgPSByZXF1aXJlKCdhbXFwbGliJyk7Cgpjb25zdCB1cmwgPSAiYW1xcDovL2d1ZXN0Omd1ZXN0QDE5Mi4xNjguMS4xNjQ6NTY3MiI7CmNvbnN0IHBvbGljZVF1ZXVlID0gIm5vdGlmeS9wb2xpY2UvdGVybWluYWwiOwoKZnVuY3Rpb24gbm90aWZ5UG9saWNlKGFsZXJ0KSB7CiAgICBhbXFwLmNvbm5lY3QodXJsKS50aGVuKGZ1bmN0aW9uKGNvbm4pIHsKICAgICAgICByZXR1cm4gY29ubi5jcmVhdGVDaGFubmVsKCkudGhlbihmdW5jdGlvbihjaCkgewogICAgICAgICAgICB2YXIgb2sgPSBjaC5hc3NlcnRRdWV1ZShwb2xpY2VRdWV1ZSwge2R1cmFibGU6IGZhbHNlfSk7CiAgICAgICAgICAgIHJldHVybiBvay50aGVuKGZ1bmN0aW9uKF9xb2spIHsKICAgICAgICAgICAgICAgIGNoLnNlbmRUb1F1ZXVlKHBvbGljZVF1ZXVlLCBCdWZmZXIuZnJvbShhbGVydCkpOwogICAgICAgICAgICAgICAgY29uc29sZS5sb2coYFNlbnQgJHthbGVydH0gb24gJHtwb2xpY2VRdWV1ZX1gKTsKICAgICAgICAgICAgICAgIHJldHVybiBjaC5jbG9zZSgpOwogICAgICAgICAgICB9KTsKICAgICAgICB9KS5maW5hbGx5KGZ1bmN0aW9uKCkgeyBjb25uLmNsb3NlKCk7IH0pOwogICAgfSkuY2F0Y2goY29uc29sZS53YXJuKTsKfQoKZnVuY3Rpb24gYmluMnN0cmluZyhhcnJheSkgewogICAgdmFyIHJlc3VsdCA9ICIiOwogICAgZm9yKHZhciBpID0gMDsgaSA8IGFycmF5Lmxlbmd0aDsgKytpKSB7CiAgICAgICAgcmVzdWx0ICs9IChTdHJpbmcuZnJvbUNoYXJDb2RlKGFycmF5W2ldKSk7CiAgICB9CiAgICByZXR1cm4gcmVzdWx0Owp9CgpleHBvcnRzLmhhbmRsZXIgPSBmdW5jdGlvbihjb250ZXh0LCBldmVudCkgewogICAgdmFyIHBhcnNlZEV2ZW50ID0gSlNPTi5wYXJzZShKU09OLnN0cmluZ2lmeShldmVudCkpOwogICAgdmFyIGFsZXJ0ID0gYmluMnN0cmluZyhwYXJzZWRFdmVudC5ib2R5LmRhdGEpOwoKICAgIGNvbnRleHQuY2FsbGJhY2soYWxlcnQpOwoKICAgIG5vdGlmeVBvbGljZShhbGVydCk7Cn07
    commands:
      - "npm install amqplib"
    codeEntryType: sourceCode
  platform: {}